version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"      
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis 
      - REDIS_PORT=6379  
    networks:
      - counter-net      

  redis:
    image: "redis:alpine"
    networks:
      - counter-net      

networks:
  counter-net:
    driver: bridge